# # # # # # # # # # # # # # # # # # # # #
#  SuperJukebox configuration           #
#  Version: 1.0.0                       #
#  An awesome music plugin by Utarwyn!  #
# # # # # # # # # # # # # # # # # # # # #

# Enable debugging (use this only when you have a problem with the plugin)
debug: false

# The locale of the plugin
locale: en

# Default configuration for new jukeboxes!
jukeboxconfiguration:
  settings:
    distance: 25
    volume: 100
    globalmusics: true
    autoplay: false
  permissions:
    interact: WITH_PERM
    editmusics: WITH_PERM
    editsettings: WITH_PERM